name: Build and Deploy react-native-doc
on:
  push:
    tags:
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: docs
jobs:
  get-static:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

  # https://www.basefactor.com/github-actions-docker
  build-image:
    runs-on: ubuntu-18.04
    needs: get-static
    steps: 

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t docs .

      - name: Tags
        run: |
          docker tag docs ${{ secrets.DOCKER_USER }}/docs:${{ github.sha }}
          docker tag docs ${{ secrets.DOCKER_USER }}/docs:latest