name: Build and Deploy react-native-doc
on:
  push:
    tags:
      - v*

jobs:
  get-static:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      # https://www.basefactor.com/github-actions-docker
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: docker build -t docs .

      - name: Tags
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag docs ${{ secrets.DOCKER_USER }}/docs:$VERSION
          docker tag docs ${{ secrets.DOCKER_USER }}/docs:latest
          docker push ${{ secrets.DOCKER_USER }}/docs:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/docs:latest
